### ISSUE TITLE
Student table does not populate all students for a cohort in the admin view.

### ISSUE THREAD

**Issue by BenjaminSchenk** [gschool-blue-ocean/learnlaunchnexus#64] opened 2023-08-19 03:09 UTC
Describe the bug
Student table for admin does not fully populate table with all students. For me it showed only 12 people with two people missing Olivia Wilson and Matthew Rodriguez.

To Reproduce
Select a cohort and count number of students then click on a student and count number of students in drop bar.

Expected behavior
All students Shown in the table when cohort is chosen each cohort has 14 students so you can count them to be sure.

Priority
High priority

Desktop
Windows: hp
Browser: Google

Additional context
N/A

**Comment by joelaspe** [comment] 2023-08-21 23:49
This has been solved by fixing the database and seed files. The issue is bad data, if the student is not assigned a value for all of the available assignments, the code currently skips the student. OHH-57 merge will close this issue.

**Closed as completed** 2023-08-22 17:24 UTC
